-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 00:06:01 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema irv_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema irv_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `irv_project` DEFAULT CHARACTER SET latin1 ;
USE `irv_project` ;

-- -----------------------------------------------------
-- Table `irv_project`.`Voters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irv_project`.`Voters` ;

CREATE TABLE IF NOT EXISTS `irv_project`.`Voters` (
  `voter-id` INT(11) NOT NULL AUTO_INCREMENT,
  `first-name` VARCHAR(45) NULL DEFAULT NULL,
  `last-name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`voter-id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `irv_project`.`Polls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irv_project`.`Polls` ;

CREATE TABLE IF NOT EXISTS `irv_project`.`Polls` (
  `poll-id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `poll-code` CHAR(8) NOT NULL,
  `available` TINYINT(1) NOT NULL DEFAULT '0',
  `voting-open` TIMESTAMP NULL DEFAULT NULL,
  `voting-closed` TIMESTAMP NULL DEFAULT NULL,
  `creator` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`poll-id`),
  INDEX `fk_voter-id_polls_idx` (`creator` ASC),
  CONSTRAINT `fk_voter-id_polls`
    FOREIGN KEY (`creator`)
    REFERENCES `irv_project`.`Voters` (`voter-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `irv_project`.`Choices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irv_project`.`Choices` ;

CREATE TABLE IF NOT EXISTS `irv_project`.`Choices` (
  `choice-id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `poll-id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`choice-id`),
  INDEX `fk_poll-id_choices_idx` (`poll-id` ASC),
  CONSTRAINT `fk_poll-id_choices`
    FOREIGN KEY (`poll-id`)
    REFERENCES `irv_project`.`Polls` (`poll-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `irv_project`.`Voters-Polls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irv_project`.`Voters-Polls` ;

CREATE TABLE IF NOT EXISTS `irv_project`.`Voters-Polls` (
  `voter-id` INT(11) NOT NULL,
  `poll-id` INT(11) NOT NULL,
  PRIMARY KEY (`voter-id`, `poll-id`),
  INDEX `fk_poll-id_voter-polls_idx` (`poll-id` ASC),
  CONSTRAINT `fk_poll-id_voters-polls`
    FOREIGN KEY (`poll-id`)
    REFERENCES `irv_project`.`Polls` (`poll-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voter-id_voters-polls`
    FOREIGN KEY (`voter-id`)
    REFERENCES `irv_project`.`Voters` (`voter-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `irv_project`.`Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irv_project`.`Votes` ;

CREATE TABLE IF NOT EXISTS `irv_project`.`Votes` (
  `vote-id` INT(11) NOT NULL AUTO_INCREMENT,
  `rank` INT(11) NOT NULL,
  `vote-cast` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `choice-id` INT(11) NULL DEFAULT NULL,
  `poll-id` INT(11) NULL DEFAULT NULL,
  `voter-id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`vote-id`),
  INDEX `fk_choice-id_choices_idx` (`choice-id` ASC),
  INDEX `fk_poll-id_choices_idx` (`poll-id` ASC),
  INDEX `fk_voter-id_choices_idx` (`voter-id` ASC),
  CONSTRAINT `fk_choice-id_votes`
    FOREIGN KEY (`choice-id`)
    REFERENCES `irv_project`.`Choices` (`choice-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll-id_votes`
    FOREIGN KEY (`poll-id`)
    REFERENCES `irv_project`.`Polls` (`poll-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voter-id_votes`
    FOREIGN KEY (`voter-id`)
    REFERENCES `irv_project`.`Voters` (`voter-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
